apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
spec:
  hosts:
    - ratings.service.consul
  http:
  - match:
    - headers:
        cookie:
          regex: "^(.*?;)?(user=jason)(;.*)?$"
    fault:
      delay:
        percent: 100
        fixedDelay: 2s
    route:
    - destination:
        host: ratings.service.consul
        subset: v1
  - route:
    - destination:
        host: ratings.service.consul
        subset: v1
